import React, { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import JobForm from "../../features/jobs/components/JobForm";
import JobPreview from "../../features/jobs/components/JobPreview";
import Button from "../../components/ui/Button";
import { createJob, getJobById, updateJob } from "../../services/job.service";
import api from "../../services/api";
import { Sparkles, Wand2 } from "lucide-react";
import { toast } from "react-hot-toast";

export default function JobPosting() {
    const navigate = useNavigate();
    const { jobId } = useParams();
    const isEditMode = Boolean(jobId);

    const [formData, setFormData] = useState({
        title: "",
        company: "Tech Corp", // Default
        location: "",
        ctc: "",
        deadline: "",
        description: "",
        requirements: "",
        type: "Full-time",
    });

    const [loading, setLoading] = useState(false);
    const [generating, setGenerating] = useState(false);
    const [error, setError] = useState("");

    useEffect(() => {
        if (isEditMode && jobId) {
            const fetchJob = async () => {
                try {
                    const data = await getJobById(jobId);
                    if (data && data.job) {
                        const job = data.job;
                        setFormData({
                            title: job.title,
                            company: job.company,
                            location: job.location,
                            ctc: job.salary,
                            deadline: job.deadline ? new Date(job.deadline).toISOString().split('T')[0] : "",
                            description: job.description,
                            requirements: Array.isArray(job.requirements) ? job.requirements.join("\n") : job.requirements,
                            type: job.type
                        });
                    }
                } catch (err) {
                    toast.error("Failed to load job details");
                    navigate("/jobs/my");
                }
            };
            fetchJob();
        }
    }, [isEditMode, jobId, navigate]);

    // Generate Job Details with AI
    const handleAIFill = async () => {
        if (!formData.title) {
            toast.error("Please enter a Job Title first!");
            return;
        }

        setGenerating(true);
        try {
            const resData = await api.post<{ description: string; requirements: string; salary: string }>("/ai/generate-job", { title: formData.title });
            const { description, requirements, salary } = resData.data;

            setFormData(prev => ({
                ...prev,
                description: description,
                requirements: requirements,
                ctc: salary,
                location: prev.location || "Hybrid / Remote"
            }));

            toast.success("Job details generated by AI!", { icon: "✨" });
        } catch (err) {
            toast.error("AI Generation failed. Try again.");
        } finally {
            setGenerating(false);
        }
    };

    const handlePostJob = async () => {
        setLoading(true);
        setError("");

        try {
            const payload = {
                title: formData.title,
                company: formData.company,
                location: formData.location,
                type: formData.type,
                salary: formData.ctc,
                description: formData.description,
                requirements: typeof formData.requirements === 'string'
                    ? formData.requirements.split(/[\n,]+/).map(req => req.trim()).filter(Boolean)
                    : formData.requirements,
                deadline: formData.deadline
            };

            if (isEditMode && jobId) {
                await updateJob(jobId, payload);
                toast.success("Job Updated Successfully!");
            } else {
                await createJob(payload);
                toast.success("Job Posted Successfully!");
            }
            navigate("/jobs/my");

        } catch (err: any) {
            console.error(err);
            setError(err.response?.data?.message || "Failed to save job");
            toast.error("Failed to save job");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="animate-in fade-in zoom-in duration-500 pb-10">
            <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight text-slate-900 bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-purple-600 w-fit">
                        {isEditMode ? "Edit Job Posting" : "Create Job Posting"}
                    </h1>
                    <p className="text-slate-500 mt-1">
                        {isEditMode ? "Update your job listing details." : "Post a new opportunity efficiently with AI assistance."}
                    </p>
                </div>

                <button
                    onClick={handleAIFill}
                    disabled={generating}
                    className="flex items-center gap-2 bg-gradient-to-r from-purple-600 to-indigo-600 text-white px-5 py-2.5 rounded-xl hover:shadow-lg hover:shadow-purple-200 transition-all font-semibold disabled:opacity-70 active:scale-95"
                >
                    {generating ? (
                        <>
                            <Sparkles className="h-4 w-4 animate-spin" />
                            Generating Magic...
                        </>
                    ) : (
                        <>
                            <Wand2 className="h-4 w-4" />
                            Auto-Fill with AI
                        </>
                    )}
                </button>
            </div>

            {error && (
                <div className="bg-red-50 border border-red-200 text-red-700 p-4 rounded-xl text-sm mb-8 flex items-center gap-2 shadow-sm">
                    <span className="h-2 w-2 rounded-full bg-red-500"></span>
                    {error}
                </div>
            )}

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
                <div className="space-y-6 bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-slate-200">
                    <JobForm formData={formData} setFormData={setFormData} />

                    <Button
                        onClick={handlePostJob}
                        disabled={loading}
                        className="w-full bg-slate-900 hover:bg-slate-800 text-white py-3 rounded-xl font-bold text-lg shadow-lg shadow-slate-200 transition-all mt-4"
                    >
                        {loading ? "Saving..." : (isEditMode ? "Update Job" : "Publish Job Opportunity")}
                    </Button>
                </div>

                <div className="lg:sticky lg:top-6 h-fit bg-slate-50 p-6 md:p-8 rounded-2xl border border-slate-200/60 dashed-border">
                    <div className="flex items-center justify-between mb-6">
                        <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                            <span className="bg-green-100 text-green-700 text-xs px-2 py-1 rounded-md">LIVE</span>
                            Preview
                        </h3>
                        <span className="text-xs text-slate-400">Student View</span>
                    </div>
                    <JobPreview data={formData} />
                </div>
            </div>
        </div>
    );
}

// Add simple CSS for dashed border visualization if needed or rely on Tailwind
// .dashed-border { border-style: dashed; }
