events {}

http {

  upstream frontend {
    server frontend:80;
  }

  upstream backend {
    server backend:5000;
  }

  upstream ai {
    server ai-gateway:8000;
  }

  server {
    listen 80;

    # ---------- FRONTEND ----------
    location / {
      proxy_pass http://frontend;
    }

    # ---------- BACKEND ----------
    location /api/ {
      proxy_pass http://backend;
    }

    # ---------- AI ----------
    location /ai/ {
      proxy_pass http://ai;
    }

  }
}
